# Generated by Django 5.1.2 on 2025-11-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', '初級 (9x9, 10個)'), ('medium', '中級 (16x16, 40個)'), ('hard', '上級 (16x30, 99個)')], max_length=10)),
                ('time_seconds', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'time_seconds'],
            },
        ),
    ]
